name: Build and Publish Image
run-name: Build and Publish Image [${{inputs.selected_environment}}]

on:
  workflow_dispatch:
    inputs:
      selected_environment:
        type: environment
        description: SELECT ENVIRONMENT
        required: true

jobs:
  build-and-deploy-in-acr:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.selected_environment }}
    steps:
      - name: Test Environment
        run: echo "${{ vars.VALUE }}"
