name: Build and Publish Image
run-name: Build and Publish Image [${{inputs.selected_environment}}]

on:
  workflow_dispatch:
    inputs:
      selected_environment:
        type: environment
        description: SELECT ENVIRONMENT
        required: true

jobs:
  build-and-deploy-in-acr:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.selected_environment }}
    steps:
      - name: Test Environment
        run: echo "${{ vars.VALUE }}"

      - name: Setup Workflow Parameters
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./parameters.json
        env:
          parameters.env.value: ${{ vars.HOME_URL }}
          parameters.appSettings.value.Workflows.SampleOne.FlowState: 'FIRST'
          parameters.appSettings.value.Workflows.SampleTwo.FlowState: 'SECOND'

      - name: Display Prameters
        run: echo "$(<parameters.json )"

      
          
